# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobinsec < Formula
  desc "Gobinsec"
  homepage "https://github.com/intercloud/gobinsec"
  version "0.10.0"
  license "MPL"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.0/gobinsec_darwin_arm64.tar.gz"
      sha256 "3d7dc474320dff3eb8845899e51f61106c97c63af61e29240e6a06fcba0f2025"

      def install
        bin.install "gobinsec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.0/gobinsec_darwin_x86_64.tar.gz"
      sha256 "d001282f01b1ac23eec8befde98e3f3d906c4559de0f598d4ece2d0545390434"

      def install
        bin.install "gobinsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.0/gobinsec_linux_arm64.tar.gz"
      sha256 "f6ce1cb046b3c21f7e951c8a875867fd3c738c6db8f7b1370504d4003edc6a73"

      def install
        bin.install "gobinsec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.0/gobinsec_linux_x86_64.tar.gz"
      sha256 "3c6f55f083aedee1839aa30e5595faa717255aab31b070029e405054fe4ce5a8"

      def install
        bin.install "gobinsec"
      end
    end
  end

  test do
    system "#{bin}/gobinsec -version"
  end
end
