# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobinsec < Formula
  desc "Gobinsec"
  homepage "https://github.com/intercloud/gobinsec"
  version "0.10.1"
  license "MPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.1/gobinsec_darwin_x86_64.tar.gz"
      sha256 "2ab7f4cb49da99621519dcdaea8979dab046c42e97397b476be963b6bca48d0d"

      def install
        bin.install "gobinsec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.1/gobinsec_darwin_arm64.tar.gz"
      sha256 "b2cb850b55448a3cbd8e87d3eb60884fc079990c7713fd3089fd1fbf8f9e70ac"

      def install
        bin.install "gobinsec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.1/gobinsec_linux_x86_64.tar.gz"
      sha256 "f54154009b238dd334523ed13563ed1b33bdc05520d5937a99241963e134eaa9"

      def install
        bin.install "gobinsec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intercloud/gobinsec/releases/download/v0.10.1/gobinsec_linux_arm64.tar.gz"
      sha256 "2960267a5425ba208559497b09931183786bddb2a624359dd418e3f72a2677c3"

      def install
        bin.install "gobinsec"
      end
    end
  end

  test do
    system "#{bin}/gobinsec -version"
  end
end
